### ISSUE TITLE
[Feature] 닉네임 생성 기능 구현

### ISSUE THREAD

**Issue by MuchanKim** [DigiLabChallengeHackathon/bewavoca-iOS#16]
## 📝 Description
> 어떤 이슈인지 설명해주세요.

닉네임 생성 뷰모델 구현
</br>

## ✅ To-do
> 작업 단위를 체크박스로 만들어주세요.

- [x] 상태 관리 기능 - 닉네임 입력 값, 로딩, 에러 등
- [x] API 호출 처리 기능 - 사용자 등록 
- [ ] 사용자 데이터 관리 기능
- [x] MapView로 화면 전환 기능

</br>

## 📋 ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
