### ISSUE TITLE
[Feature] CharacterSelectionView 그리기

### ISSUE THREAD

**Issue by MuchanKim** [DigiLabChallengeHackathon/bewavoca-iOS#21]
## 📝 Description
> 어떤 이슈인지 설명해주세요.

CharacterSelectionView 그리기

</br>

## ✅ To-do
> 작업 단위를 체크박스로 만들어주세요.

- [x] 이미지 리소스 추가
- [x] 함께하기 버튼 터치 시 유저 캐릭터 값 업데이트 
- [x] 현재 스테이지로 값으로 해금 상태 구분하기
- [x] 캐릭터 설명은 목데이터로 사용
- [x] 기기별 레이아웃 확인

</br>

## 📋 ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
