### ISSUE TITLE
[Feature] NewCharacterView 그리기

### ISSUE THREAD

**Issue by MuchanKim** [DigiLabChallengeHackathon/bewavoca-iOS#28]
## 📝 Description
> 어떤 이슈인지 설명해주세요.

NewCharacterView UI구현입니다.
</br>

## ✅ To-do
> 작업 단위를 체크박스로 만들어주세요.

- [ ] 이미지 리소스 추가
- [ ] 텍스트, 캐릭터, 버튼 단위로 배치
- [ ] 버튼 클릭 시 메인 화면으로 전환 

</br>

## 📋 ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
