### ISSUE TITLE
[Feature] RewardView 그리기 및 NewCharacterView와 연결

### ISSUE THREAD

**Issue by MuchanKim** [DigiLabChallengeHackathon/bewavoca-iOS#29]
## 📝 Description
> 어떤 이슈인지 설명해주세요.

새로운 캐릭터뷰를 만드는데 너무 단순해서 리워드 뷰까지 같이 작업해서 붙일게요!
</br>

## ✅ To-do
> 작업 단위를 체크박스로 만들어주세요.

- [ ] 이미지 리소스 추가 - 피그마 리소스에 배경 캐릭터 분리해서 업로드 할 것
- [ ] 클리어 스테이지 넘버에 따른 캐릭터 변경 ex) 1스테이지 깰 시 동백 스플래시 -> 동백 캐릭터 획득
- [ ] 캐릭터 별 텍스트 구분하여 적용

</br>

## 📋 ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.

아래 이슈에서 추가된 이슈입니다.
- #28
