### ISSUE TITLE
[Feature] 메인 뷰 그리기 

### ISSUE THREAD

**Issue by delightPIP** [DigiLabChallengeHackathon/bewavoca-iOS#3]
## 📝 Description
>  MainView 구현

</br>

## ✅ To-do
> 작업 단위를 체크박스로 만들어주세요.

- [ ] 애셋 추가
- [ ] svg path 를 이용한 shape 구현
- [ ] 공통 사용 배경 View 추가
- [ ] map 버튼 클릭 시 화면 이동
- [ ] 오픈 된 맵, 현재 진행 중인 맵 구분 및 구현

</br>

## 📋 ETC (참고 자료)
> 
- SVG 관련
 https://velog.io/@softer/svg-01
