### ISSUE TITLE
[Feature] OnboardingView 그리기

### ISSUE THREAD

**Issue by MuchanKim** [DigiLabChallengeHackathon/bewavoca-iOS#33]
## 📝 Description
> 어떤 이슈인지 설명해주세요.

온보딩 뷰 그리기 작업입니다.
</br>

## ✅ To-do
> 작업 단위를 체크박스로 만들어주세요.

- [ ] 이미지 리소스 추가
- [ ] 온보딩 화면 UI 구현
- [ ] 화면 전환 구현: 마지막 온보딩뷰에서 닉네임생성뷰로 이동

</br>

## 📋 ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.

<img src="https://github.com/user-attachments/assets/64ab89ff-0c40-4bb1-8d05-d6b8c60090b9" width="300"/>
