### ISSUE TITLE
[Feature] AppEntryView 구현

### ISSUE THREAD

**Issue by MuchanKim** [DigiLabChallengeHackathon/bewavoca-iOS#37]
## 📝 Description
> 어떤 이슈인지 설명해주세요.

앱 진입 뷰 구현입니다.
uuid 식별으로 온보딩 or 메인뷰로 이동하는 로직을 담고 있습니다.
목데이터로 구현 예정입니다.

관련 이슈
- #36 

</br>

## ✅ To-do
> 작업 단위를 체크박스로 만들어주세요.

- [x] uuid 여부 체크. 없다면 신규유저, 있다면 기존유저로 구분합니다.
- [x] 신규유저는 온보딩뷰로 전환해야 합니다.
- [x] 기존유저는 메인뷰로 전환해야 합니다. 
- [x] 기존유저는 서버에서 값을 아직 못받아오기에 목데이터를 사용하도록 구현해야합니다.

</br>

## 📋 ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
