### ISSUE TITLE
[Feature] 스테이지 뷰 그리기

### ISSUE THREAD

**Issue by MuchanKim** [DigiLabChallengeHackathon/bewavoca-iOS#4]
## 📝 Description
> 어떤 이슈인지 설명해주세요.

스테이지 뷰 그리기
</br>

## ✅ To-do
> 작업 단위를 체크박스로 만들어주세요.

- [ ] 에셋 추가
- [ ] 현재 스테이지, 클리어 스테이지, 미해금 스테이지 구분
- [ ] 클리어 스테이지에 현재 캐릭터 에셋 추가하기
- [ ] 뒤로가기 버튼 구현
- [ ] 스테이지 이동 구현

</br>

## 📋 ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.
